{{- range $name, $sm := .Values.vmServiceScrapes }}
---
kind: VMServiceScrape
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  endpoints:
    {{- include "helpers.tplvalues.render" (dict "value" .endpoints "context" $) | nindent 4 }}
  selector:
    matchLabels:
      {{- include "helpers.app.selectorLabels" $ | nindent 6 }}
      {{- with $.Values.generic.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end -}}
      {{- with .extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end -}}
  {{- with .sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .streamParse }}
  streamParse: {{ . }}
  {{- end }}
{{- end }}

{{- range $name, $sm := .Values.vmservicescrapes }}
---
kind: VMServiceScrape
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
spec:
  endpoints:
    {{- include "helpers.tplvalues.render" (dict "value" .endpoints "context" $) | nindent 4 }}
  selector:
    matchLabels:
      {{- include "helpers.app.selectorLabels" $ | nindent 6 }}
      {{- with $.Values.generic.extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end -}}
      {{- with .extraSelectorLabels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 6 }}{{- end -}}
  {{- with .sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .streamParse }}
  streamParse: {{ . }}
  {{- end }}
{{- end }} 